services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    # LAN access
    ports:
      - "9000:9000"
    networks:
      - containers_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/streamlab/data/portainer:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - /opt/streamlab/secrets/watchtower.env
    environment:
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_TEMPLATE: "@everyone {{range .}}{{.Message}}{{println}}{{end}}"
      WATCHTOWER_NOTIFICATION_SKIP_TITLE: "true"
      DOCKER_API_VERSION: "1.44"
    command: >
      --monitor-only
      --label-enable
      --schedule "0 30 4 * * *"
      --cleanup
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    dns:
      - 1.1.1.1
      - 1.0.0.1
    env_file:
      - /opt/streamlab/secrets/cloudflared.env
    networks:
      - containers_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    # LAN access
    ports:
      - "8081:80"
    networks:
      - containers_network
    volumes:
      - /opt/streamlab:/srv:ro
      - /opt/streamlab/data/filebrowser:/database
    command:
      - "--database=/database/filebrowser.db"
      - "--root=/srv"
    user: "1000:1000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3003:3001"
    networks:
      - containers_network
    volumes:
      - /opt/streamlab/data/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  containers_network:
    external: true
